import express from "express";
import dotenv from "dotenv";
import{authRouter} from './routes/auth.routes.js';
import  errorHandler from "./middleware/error.middleware.js";
import connectDB from "./config/db.js";
import requestLogger from "./middleware/requestLogger.middleware.js";
import { cartRouter } from "./routes/cart.routes.js";
import { adminAnalyticsRouter } from "./routes/adminAnalytics.routes.js";
import { categoryRouter } from "./routes/category.routes.js";
import { couponRouter } from "./routes/coupon.routes.js";
import { orderRouter } from "./routes/order.routes.js";
import { paymentRouter } from "./routes/payment.routes.js";
dotenv.config();
connectDB();
const app = express();
app.use(express.json());
app.use(requestLogger);
app.use("/auth", authRouter);
app.use("/cart" , cartRouter);
app.use("/admin" , adminAnalyticsRouter);
app.use("/category" , categoryRouter);
app.use("/coupon" , couponRouter);
app.use("/order" , orderRouter);
app.use("/payment" , paymentRouter);
app.use(errorHandler);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
